Repository Frezyx/talker, pull requests merged in 2024-11, with the labels that each got.

#270 Bug fixing in sample code
  examples/shop_app_example/android/app/build.gradle
  examples/shop_app_example/android/app/src/debug/AndroidManifest.xml
  examples/shop_app_example/android/app/src/main/AndroidManifest.xml
  examples/shop_app_example/android/app/src/profile/AndroidManifest.xml
  examples/shop_app_example/android/build.gradle
  examples/shop_app_example/android/gradle.properties
  examples/shop_app_example/android/gradle/wrapper/gradle-wrapper.properties
  examples/shop_app_example/android/settings.gradle
  examples/shop_app_example/pubspec.lock
  examples/shop_app_example/pubspec.yaml
Labels: dependencies, platform

#275 fix: TalkerLog pen color
  packages/talker/lib/src/talker.dart
Labels: release, bugfix

#276 feat(talker_dio_logger): add enable option to control log output
  packages/talker_dio_logger/lib/talker_dio_logger_interceptor.dart
  packages/talker_dio_logger/lib/talker_dio_logger_settings.dart
Labels: enhancement, addons

#283 Rename logTyped to logCustom and add deprecated annotation for logTyped
  README.md
  packages/talker/example/talker_example.dart
  packages/talker/lib/src/talker.dart
  packages/talker/test/talker_settings_test.dart
  packages/talker/test/talker_test.dart
  packages/talker_bloc_logger/lib/talker_bloc_logger_observer.dart
  packages/talker_dio_logger/lib/talker_dio_logger_interceptor.dart
  packages/talker_flutter/example/lib/extended_example/extended_example.dart
  packages/talker_flutter/lib/src/observers/router_observer.dart
  packages/talker_http_logger/lib/talker_http_logger.dart
  packages/talker_riverpod_logger/lib/talker_riverpod_logger_observer.dart
Labels: refactoring

#285 Make talker_dio_logger encoder constant private
  packages/talker_dio_logger/lib/dio_logs.dart
Labels: refactoring

#272 More flexible interaction with custom logs (TalkerLogType -> String key)
  README.md
  docs/assets/logger/custom_log.png
  examples/shop_app_example/.gitignore
  examples/shop_app_example/ios/Podfile.lock
  examples/shop_app_example/ios/Runner/AppDelegate.swift
  examples/shop_app_example/lib/main.dart
  examples/shop_app_example/lib/ui/theme.dart
  examples/shop_app_example/lib/utils/good_log.dart
  examples/shop_app_example/pubspec.lock
  examples/shop_app_example/pubspec.yaml
  packages/talker/example/talker_example.dart
  packages/talker/lib/src/extensions/extensions.dart
  packages/talker/lib/src/models/talker_data.dart
  packages/talker/lib/src/settings.dart
  packages/talker/lib/src/talker.dart
  packages/talker/lib/src/talker_key.dart
  packages/talker/lib/src/utils/error_handler.dart
  packages/talker/pubspec.yaml
  packages/talker/test/talker_custom_log_test.dart
  packages/talker/test/talker_settings_test.dart
  packages/talker/test/talker_test.dart
  packages/talker_dio_logger/.gitignore
  packages/talker_dio_logger/example/.gitignore
  packages/talker_dio_logger/example/pubspec.lock
  packages/talker_flutter/.flutter-plugins
  packages/talker_flutter/.gitignore
  packages/talker_flutter/example/.gitignore
  packages/talker_flutter/example/ios/Podfile.lock
  packages/talker_flutter/example/ios/Runner/AppDelegate.swift
  packages/talker_flutter/example/lib/main.dart
  packages/talker_flutter/example/linux/flutter/ephemeral/.plugin_symlinks/share_plus
  packages/talker_flutter/example/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
  packages/talker_flutter/example/pubspec.lock
  packages/talker_flutter/example/pubspec_overrides.yaml
  packages/talker_flutter/lib/src/extensions/talker_data.dart
  packages/talker_flutter/lib/src/ui/theme/talker_screen_theme.dart
Labels: enhancement, release, core, console

#286 Fix static analysis issues
  packages/talker_flutter/lib/src/ui/theme/talker_screen_theme.dart
Labels: release, bugfix
